# Generated by Django 6.1.1 on 2026-09-11 15:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Nom du destinataire')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du destinataire')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du certificat')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('issuer_name', models.CharField(max_length=255, verbose_name='Organisme émetteur')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('certificate_hash', models.CharField(blank=True, max_length=66)),
                ('tx_hash', models.CharField(blank=True, max_length=66, verbose_name='Hash de transaction')),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('issuer_wallet', models.CharField(blank=True, max_length=42, verbose_name='Wallet émetteur')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('registered', 'Enregistré'), ('revoked', 'Révoqué'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('revocation_reason', models.TextField(blank=True, verbose_name='Raison de révocation')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_tx_hash', models.CharField(blank=True, max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-created_at'],
            },
        ),
    ]
